# Generated by Django 5.2.12 on 2026-03-14 07:53

import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Habit",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("place", models.CharField(max_length=50, verbose_name="Место")),
                ("time", models.TimeField(verbose_name="Время")),
                ("action", models.TextField(verbose_name="Действие")),
                ("is_pleasant_habit", models.BooleanField(verbose_name="Приятная привычка")),
                (
                    "periodicity",
                    models.PositiveSmallIntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(7),
                        ],
                        verbose_name="Периодичность (день)",
                    ),
                ),
                ("reward", models.TextField(blank=True, null=True, verbose_name="Вознаграждение")),
                (
                    "complete_time",
                    models.DurationField(
                        default=datetime.timedelta(seconds=120),
                        validators=[django.core.validators.MaxValueValidator(datetime.timedelta(seconds=120))],
                        verbose_name="Время на выполнение",
                    ),
                ),
                ("is_public", models.BooleanField(verbose_name="Признак публичности")),
                (
                    "related_habit",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"is_pleasant_habit": True},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dependent_habits",
                        to="habits.habit",
                        verbose_name="Связанная привычка",
                    ),
                ),
            ],
            options={
                "verbose_name": "привычка",
                "verbose_name_plural": "привычки",
                "ordering": ["user"],
            },
        ),
    ]
